// examples/vue2/src/components/TabContainer.vue
<template>
  <div class="tab-container">
    <!-- Tab 导航 -->
    <div class="tabs">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        :class="['tab-button', { active: activeTab === tab.id }]"
        @click="activeTab = tab.id"
      >
        {{ tab.name }}
      </button>
    </div>

    <!-- Tab 内容 -->
    <div class="tab-content">
      <!-- 会话纪要组件 -->
      <div v-show="activeTab === 'conversation-summary'" class="tab-panel">
        <ConversationSummaryTab />
      </div>

      <!-- 预留的其他组件 tab -->
      <div v-show="activeTab === 'component-2'" class="tab-panel">
        <Component2Tab />
      </div>

      <div v-show="activeTab === 'component-3'" class="tab-panel">
        <Component3Tab />
      </div>
    </div>
  </div>
</template>

<script>
// Tab 容器组件 - 管理多个组件示例的展示
// 设计思想：
// 1. 使用 data 函数来定义响应式状态
// 2. 提供统一的 tab 导航界面
// 3. 通过 v-show 指令来控制显示对应的组件内容
// 4. 支持扩展更多的组件示例
import ConversationSummaryTab from './ConversationSummaryTab.vue';
import Component2Tab from './Component2Tab.vue';
import Component3Tab from './Component3Tab.vue';

export default {
  name: 'TabContainer',
  components: {
    ConversationSummaryTab,
    Component2Tab,
    Component3Tab
  },
  data() {
    return {
      // 当前激活的 tab
      activeTab: 'conversation-summary',

      // Tab 配置
      tabs: [
        { id: 'conversation-summary', name: '会话纪要' },
        { id: 'component-2', name: '组件 2' },
        { id: 'component-3', name: '组件 3' }
      ]
    };
  }
};
</script>

<style scoped>
.tab-container {
  /* Tab 容器样式 */
}

.tabs {
  display: flex;
  border-bottom: 1px solid #e0e0e0;
  margin-bottom: 20px;
}

.tab-button {
  padding: 12px 24px;
  border: none;
  background: none;
  cursor: pointer;
  font-size: 16px;
  border-bottom: 2px solid transparent;
  transition: all 0.3s ease;
}

.tab-button:hover {
  background-color: #f5f5f5;
}

.tab-button.active {
  border-bottom-color: #007bff;
  color: #007bff;
  font-weight: bold;
}

.tab-content {
  min-height: 400px;
}

.tab-panel {
  padding: 20px 0;
}
</style>

// examples/react/src/components/TabContainer.jsx
import { useState } from 'react';
import ConversationSummaryTab from './ConversationSummaryTab';
import Component2Tab from './Component2Tab';
import Component3Tab from './Component3Tab';

// Tab 容器组件 - 管理多个组件示例的展示
// 设计思想：
// 1. 使用状态管理来控制当前激活的 tab
// 2. 提供统一的 tab 导航界面
// 3. 通过条件渲染来显示对应的组件内容
// 4. 支持扩展更多的组件示例
const TabContainer = () => {
  // 当前激活的 tab 状态
  const [activeTab, setActiveTab] = useState('conversation-summary');

  // Tab 配置数据 - 定义所有可用的 tab
  const tabs = [
    { id: 'conversation-summary', name: '会话纪要' },
    { id: 'component-2', name: '组件 2' },
    { id: 'component-3', name: '组件 3' }
  ];

  return (
    <div className="tab-container">
      {/* Tab 导航区域 */}
      <div className="tabs">
        {tabs.map(tab => (
          <button
            key={tab.id}
            className={`tab-button ${activeTab === tab.id ? 'active' : ''}`}
            onClick={() => setActiveTab(tab.id)}
          >
            {tab.name}
          </button>
        ))}
      </div>

      {/* Tab 内容区域 */}
      <div className="tab-content">
        {/* 会话纪要组件 */}
        {activeTab === 'conversation-summary' && (
          <div className="tab-panel">
            <ConversationSummaryTab />
          </div>
        )}

        {/* 预留的其他组件 tab */}
        {activeTab === 'component-2' && (
          <div className="tab-panel">
            <Component2Tab />
          </div>
        )}

        {activeTab === 'component-3' && (
          <div className="tab-panel">
            <Component3Tab />
          </div>
        )}
      </div>
    </div>
  );
};

export default TabContainer;
